import type {Metadata} from "next";
import "./globals.css";
import Header from "@/components/header";
import { headers } from 'next/headers'
import ContextProvider from '@/context/index'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
     children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headersList = await headers();
    const cookies = headersList.get('cookie');
    return (
        <html lang="en">
        <body>
        <ContextProvider cookies={cookies}>
            <Header/>
            <main>
                {children}
            </main>
        </ContextProvider>
        </body>
        </html>
    );
}
